# Site settings
title: "Nick Thompson"
title_end: " ∙ Nick Thompson"
description: > # this means to ignore newlines until "baseurl:"
  Future description for the website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nickthompson.guru" # the base hostname & protocol for your site


# Build settings
markdown: kramdown


# Colors (hex)
color:
    
