# Site settings
title: "Nick Thompson"
title_end: " ∙ Nick Thompson"
description: > # this means to ignore newlines until "baseurl:"
  Nick Thompson's website with info about him, his computer services, portfolio, and blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nickthompson.guru" # the base hostname & protocol for your site

gems:
  - jekyll-sitemap

permalink: /blog/:categories/:year/:month/:day/:title/

exclude: ["/_posts/YYYY-MM-DD-Post-Template-Title-URL.md"]

# Build settings
markdown: kramdown


colors:  #in hex code if not noted else
  primary: "#AB3C47" #"#F70031" 
  secondary: "#999" #"#33004D"
  background: "#222"
  navbar: "#000000"
  link: "#428bca"
  link_hover: "#01b2fe"
  header: "#EEE"
  footer: "#111"
  footer_heading: "#ffffff"
  footer_content: "#fff"
  text_light: "#fff"
